apiVersion: v1
kind: Namespace
metadata:
  name: hacked
---
apiVersion: v1
kind: Service
metadata:
  name: hacked-svc
  namespace: hacked
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hacked-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hacked-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hacked-app
  template:
    metadata:
      labels:
        app: hacked-app
    spec:
      containers:
      - name: hacked-app
        image: chrisley75/hello-kubernetes:v1
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: You've been hacked !
